mydjango/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('about/', views.about),
    path('post/', include('post.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='list'),
    path('new-post/', views.post_new, name='new-post'), # 반드시 slug 설정 위로 와야 함.
    path('<slug:slug>', views.post_page, name='page'), #<>사이에 빈칸이 있으면 에러난다.
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    # path('logout/', views.logout_view, name='logout'),
    path('logout/', views.logout_view, name="logout"),
]

post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)                          

    def __str__(self) -> str:
        return self.title

users/models.py
from django.db import models

# Create your models here.

mydjango/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    # return HttpResponse("Hello, world. You're at the polls index.")
    return render(request, 'index.html')

def about(request):
    # return HttpResponse("About")
    return render(request, 'about.html')

post/views.py
from django.shortcuts import render
from .models import Post
from django.contrib.auth.decorators import login_required

# Create your views here.
def post_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request,'post/post_list.html', {'posts':posts})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'post/post_page.html', {'post': post})

@login_required(login_url='users:login')
def post_new(request):
    return render(request, 'post/post_new.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate

# Create your views here.
def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect('post:list')
    else:
        form = UserCreationForm()
    return render(request, "users/register.html", { "form": form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('post:list')
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", { "form": form })

def logout_view(request):
    if request.method == "POST": 
        logout(request) 
        return redirect("post:list")

post/templates/post/post_list.html
{% extends 'layout.html' %}

{% block title %}
    Post
{% endblock %}

{% block content %}
    <section>
        <h1>Post list</h1>
        {% for post in posts %}
            <article>
                <h3>
                    <a href="{% url 'post:page' slug=post.slug %}">{{ post.title }}</a>
                </h3>
                <p>{{ post.date }}</p>
                <p>{{ post.body }}</p>
            </article>
        {% endfor %}
    </section>
{% endblock %}

post/templates/post/post_new.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}
    
{% block content %}
    <section>
        <h2>New post</h2>
        <form action="POST">
            {% csrf_token %}
            {{ form }}
            <button>Submit</button>
        </form>
        <p>
            <a href="{% url 'post:list' %}">목록으로</a>
            <a href="{% url 'post:list' %}">Go to prev article</a>
        </p>
    </section>
{% endblock %}

post/templates/post/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}
    
{% block content %}
    <section>
        <article>
            <img 
                class = 'top_banner'
                src="{{ post.banner.url }}" 
                alt="{{ post.title }}"
                />
            <h1>{{ post.title }}</h1>
            <p>{{ post.date }}</p>
            <p>{{ post.body }}</p>
            <p>{{ pk }}</p>
        </article>
        <p>
            <a href="{% url 'post:list' %}">목록으로</a>
            <a href="{% url 'post:list' %}">Go to prev article</a>
        </p>
    </section>
{% endblock %}

templates/about.html
{% extends 'layout.html' %}

{% block title %}
    about
{% endblock %}

{% block content %}
    <h2>about</h2>
    <p>this is about</p>
    <a href="/">home</a>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}
    index
{% endblock %}

{% block content %}
    <h2>home</h2>
    <p>this is home</p>
    <a href="/about">about</a>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="KO">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            No title
        {% endblock%}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/"><span>Home</span></a> | 
        <a href="/about"><span>About</span></a> | 
        {% comment %} # post에 있는 list를 가져와 {% endcomment %}
        <a href="{% url 'post:list' %}"><span>Post</span></a> |
        {% if user.is_authenticated %}
            <a href="{% url 'post:new-post' %}"><span>New</span></a> |
            <form class='logout' action="{% url 'users:logout' %}" method='post'>
                {% csrf_token %}
                <span class='logout-button'><button >logout</button></span>
            </form>    
        {% else %}
            <a href="{% url 'users:register' %}"><span>Join</span></a> |
            <a href="{% url 'users:login' %}"><span>Login</span></a> |
        {% endif %}
        <a href="/admin"><span role='img' aria-label='admin' title='admin'>👀</span></a> 
    </nav>
    <main>
        {% block content %}
            No contents
        {% endblock %}
    </main>
</body>
</html>

users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    User login
{% endblock %}

{% block content %}
    <h2>User login</h2>
    <form class='form-with-vals' action="/users/login/" method='post'>
        {% csrf_token %} 
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name='next' value='{{ request.GET.next }}'>
        {% endif %}
        <button>Submit</button>
    </form>
    <p>login</p>
    <a href="/">Home</a>
{% endblock %}

users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register new user
{% endblock %}

{% block content %}
    <h2>User Register</h2>
    <form class='form-with-vals' action="/users/register/" method='post'>
        {% csrf_token %} 
        {{ form }}
        <button>Submit</button>
    </form>
    <p>Regiter you</p>
    <a href="/">Home</a>
{% endblock %}